-- Cardápio completo 03-11: insere itens por seção, sem repetir por nome.
-- Cada item: name, category, sale_price; evita duplicata por LOWER(TRIM(name)).

INSERT INTO public.recipes (name, category, sale_price, description, sells_slice, sells_whole, slice_price, slice_weight_g, min_stock)
SELECT v.name, v.category::public.product_category, v.sale_price, v.description, true, false, v.sale_price, 250, 0
FROM (VALUES
  -- Salgados tradicionais (R$ 13-17)
  ('Coxinha com Catupiry', 'salgado', 13.00, 'Tradicional'),
  ('Kibe', 'salgado', 13.00, 'Tradicional'),
  ('Pão de Batata', 'salgado', 13.00, 'Tradicional'),
  ('Empada Palmito', 'salgado', 17.00, NULL),
  ('Empada Frango com Catupiry', 'salgado', 17.00, NULL),
  ('Empada Carne seca com abóbora', 'salgado', 17.00, NULL),
  ('Empada 3 Queijos com milho', 'salgado', 17.00, NULL),
  ('Quiche Brócolis', 'salgado', 17.00, NULL),
  ('Quiche Alho poró', 'salgado', 17.00, NULL),
  ('Quiche Queijo', 'salgado', 17.00, NULL),
  ('Coxinha', 'salgado', 15.00, NULL),
  ('Risoles', 'salgado', 15.00, NULL),
  ('Bolinho de carne', 'salgado', 15.00, NULL),
  ('Bolinho de carne com ovo', 'salgado', 15.00, NULL),
  ('Esfiha de carne', 'salgado', 15.00, NULL),
  ('Esfiha de carne com queijo', 'salgado', 15.00, NULL),
  ('Esfiha de escarola com queijo branco', 'salgado', 15.00, NULL),
  ('Esfiha de frango com Catupiry', 'salgado', 15.00, NULL),
  ('Esfiha de calabresa com Catupiry', 'salgado', 15.00, NULL),
  ('Esfiha 3 queijos', 'salgado', 15.00, NULL),
  ('Enroladinho de presunto e queijo', 'salgado', 15.00, NULL),
  ('Hamburgão', 'salgado', 15.00, NULL),
  -- Pães e lanches
  ('Pão de queijo', 'salgado', 7.00, NULL),
  ('Pão de queijo com requeijão', 'salgado', 9.50, NULL),
  ('Pão com manteiga', 'salgado', 7.00, NULL),
  ('Pão na chapa com manteiga', 'salgado', 7.50, NULL),
  ('Pão na chapa com requeijão', 'salgado', 8.50, NULL),
  ('Pão na chapa com requeijão (saída)', 'salgado', 9.00, NULL),
  ('Misto frio', 'salgado', 12.00, NULL),
  ('Misto quente', 'salgado', 13.00, NULL),
  ('Omelete', 'salgado', 10.50, NULL),
  ('Omelete com frios', 'salgado', 14.00, NULL),
  ('Pão com ovo', 'salgado', 10.00, NULL),
  ('Pão com ovo, queijo e bacon', 'salgado', 14.00, NULL),
  ('Queijo quente', 'salgado', 9.00, NULL),
  ('Queijo quente com requeijão', 'salgado', 10.00, NULL),
  ('Mortadela quente', 'salgado', 9.00, NULL),
  ('Bauru', 'salgado', 14.00, NULL),
  ('Americano (lanche)', 'salgado', 17.00, NULL),
  ('Adicional (bacon, ovo, presunto, queijo)', 'salgado', 3.00, 'Cada'),
  -- Cafés e bebidas quentes
  ('Café coado', 'bebida', 3.50, 'Pequeno'),
  ('Café coado grande', 'bebida', 5.50, 'Grande'),
  ('Café coado com leite', 'bebida', 4.50, NULL),
  ('Café coado com leite grande', 'bebida', 6.00, 'Grande'),
  ('Café expresso', 'bebida', 6.50, NULL),
  ('Café expresso grande', 'bebida', 7.50, 'Grande'),
  ('Café expresso com leite', 'bebida', 8.50, NULL),
  ('Café expresso com leite grande', 'bebida', 9.50, 'Grande'),
  ('Café expresso com Chantilly', 'bebida', 9.50, NULL),
  ('Café expresso com Chantilly grande', 'bebida', 10.50, 'Grande'),
  ('Chá quente', 'bebida', 8.00, NULL),
  ('Cappuccino', 'bebida', 8.00, NULL),
  ('Cappuccino grande', 'bebida', 10.50, 'Grande'),
  ('Chocolate quente', 'bebida', 7.50, NULL),
  ('Chocolate gelado', 'bebida', 7.50, NULL),
  ('Chocolate batido', 'bebida', 10.00, NULL),
  ('Chocolate cremoso', 'bebida', 12.00, NULL),
  ('Leite quente', 'bebida', 3.00, NULL),
  ('Leite quente grande', 'bebida', 15.00, 'Jarra - servido 7h às 12h'),
  -- Hambúrgueres
  ('Cheese Burguer Tradicional', 'salgado', 20.00, NULL),
  ('Cheese Egg', 'salgado', 21.00, NULL),
  ('Cheese Salada', 'salgado', 21.00, NULL),
  ('Cheese Bacon', 'salgado', 24.00, NULL),
  ('Cheese Egg Salada', 'salgado', 22.00, NULL),
  ('Cheese Tudo', 'salgado', 30.00, NULL),
  ('Dú Café', 'salgado', 34.90, 'Pão Brioche, 2 burguers, cheddar e maionese da casa'),
  ('Hambúrguer Americano', 'salgado', 40.90, 'Pão Brioche, 2 burguers, cheddar, maionese, ovo e bacon'),
  ('Saladeiro', 'salgado', 39.90, 'Pão Brioche, 2 burguers, alface, tomate, bacon, cheddar, molho barbecue'),
  ('Mix Cocho', 'salgado', 43.90, 'Pão Brioche, 3 burguers, alface, tomate, bacon, cheddar e catupiry'),
  ('Porção de fritas', 'salgado', 15.00, NULL),
  -- Açaí e milk shake
  ('Açaí com Leite Ninho', 'doce', 26.90, NULL),
  ('Açaí Chocolate', 'doce', 26.90, NULL),
  ('Açaí Morango', 'doce', 26.90, NULL),
  ('Açaí Doce de leite com Paçoca', 'doce', 28.90, NULL),
  ('Açaí Nutella', 'doce', 30.90, NULL),
  ('Açaí Nutella com Leite Ninho', 'doce', 30.90, NULL),
  ('Açaí Ovomaltine', 'doce', 30.90, NULL),
  ('Milk Shake', 'bebida', 26.90, 'Sabores diversos'),
  ('Bolo pedaço (sabores)', 'bolo', 25.00, NULL),
  ('Açaí com granola', 'doce', 22.00, 'Banana ou morango'),
  ('Adicional açaí (banana, morango, leite condensado, etc)', 'doce', 2.00, 'Cada'),
  -- Tortinhas
  ('Tortinha Morango', 'torta', 15.00, NULL),
  ('Tortinha Limão', 'torta', 13.00, NULL),
  ('Tortinha Brigadeiro', 'torta', 13.00, NULL),
  ('Tortinha Uva', 'torta', 17.00, NULL),
  ('Tortinha Banoffe', 'torta', 17.00, NULL),
  ('Tortinha Nutella', 'torta', 17.00, NULL),
  ('Tortinha Nutella com Morango', 'torta', 17.00, NULL),
  ('Tortinha Holandesa', 'torta', 17.00, NULL),
  ('Tortinha Pudim', 'torta', 13.00, NULL),
  -- Bebidas
  ('Refrigerante lata', 'bebida', 8.00, NULL),
  ('Schweppes', 'bebida', 8.00, NULL),
  ('Refrigerante 600ml', 'bebida', 13.00, NULL),
  ('Refrigerante 2 litros', 'bebida', 20.00, NULL),
  ('Suco Del Valle 1 litro', 'bebida', 15.00, NULL),
  ('Suco de lata', 'bebida', 7.50, NULL),
  ('Água sem gás', 'bebida', 5.00, NULL),
  ('Água com gás', 'bebida', 6.00, NULL),
  ('Água Tônica', 'bebida', 8.00, NULL),
  ('Água de coco', 'bebida', 9.00, NULL),
  ('Toddynho', 'bebida', 6.00, NULL),
  ('H2O', 'bebida', 13.00, NULL),
  ('Sprite Lemon', 'bebida', 13.00, NULL),
  ('Guaraviton', 'bebida', 6.50, NULL),
  ('Long Neck Heineken', 'bebida', 12.00, NULL),
  ('Cerveja Original lata', 'bebida', 6.00, NULL),
  ('Budweiser lata', 'bebida', 6.00, NULL),
  ('Suco Laranja jarra pequena', 'bebida', 15.00, NULL),
  ('Suco Limão jarra pequena', 'bebida', 15.00, NULL),
  ('Suco Laranja jarra grande', 'bebida', 25.00, NULL),
  ('Suco Limão jarra grande', 'bebida', 25.00, NULL),
  -- Bolos por kg (R$ 102)
  ('Bolo Brigadeiro', 'bolo', 102.00, 'Massa de chocolate, recheio de brigadeiro, coberto de chocolate e granulado. Preço por kg'),
  ('Bolo Cocada', 'bolo', 102.00, 'Massa branca, recheio de cocada cremosa. Preço por kg'),
  ('Bolo Crocante', 'bolo', 102.00, 'Amendoim caramelizado e doce de leite. Preço por kg'),
  ('Bolo Mousse de Limão', 'bolo', 102.00, 'Mousse de limão, chantilly e raspas de limão. Preço por kg'),
  ('Bolo Mousse de Maracujá', 'bolo', 102.00, 'Calda de maracujá, mousse e geleia. Preço por kg'),
  ('Bolo Pêssego com Creme', 'bolo', 102.00, 'Pêssego e creme, chantilly. Preço por kg'),
  ('Bolo Prestígio', 'bolo', 102.00, 'Chocolate e cocada. Preço por kg'),
  -- Bolos por kg (R$ 115)
  ('Bolo Abacaxi com Creme', 'bolo', 115.00, 'Abacaxi e creme, chantilly. Preço por kg'),
  ('Bolo Ameixa com Doce de Leite', 'bolo', 115.00, 'Ameixa e doce de leite. Preço por kg'),
  ('Bolo Bem Casado', 'bolo', 115.00, 'Doce de leite. Preço por kg'),
  ('Bolo Morango', 'bolo', 115.00, 'Morango e creme. Preço por kg'),
  ('Bolo Abacaxi com Doce de Leite', 'bolo', 115.00, 'Abacaxi e doce de leite. Preço por kg'),
  ('Bolo Bicho de Pé', 'bolo', 115.00, 'Bicho de pé, chantilly. Preço por kg'),
  ('Bolo Brigadeiro com Mousse de Maracujá', 'bolo', 115.00, 'Brigadeiro e mousse de maracujá. Preço por kg'),
  ('Bolo Casadinho', 'bolo', 115.00, 'Cocada e doce de leite. Preço por kg'),
  ('Bolo Dois Amores', 'bolo', 115.00, 'Cocada e brigadeiro. Preço por kg'),
  ('Bolo Floresta Branca', 'bolo', 115.00, 'Cereja e chantilly. Preço por kg'),
  ('Bolo Floresta Negra', 'bolo', 115.00, 'Cereja e chocolate. Preço por kg'),
  ('Bolo Merengue', 'bolo', 115.00, 'Morango, pêssego e abacaxi. Preço por kg'),
  ('Bolo Mousse de Chocolate', 'bolo', 115.00, 'Mousse de chocolate. Preço por kg'),
  ('Bolo Sonho de Valsa', 'bolo', 115.00, 'Brigadeiro e Sonho de Valsa. Preço por kg'),
  ('Bolo Frutas', 'bolo', 115.00, 'Frutas frescas. Preço por kg'),
  -- Bolos por kg (R$ 129)
  ('Bolo Mousse de Chocolate Preto e Branco', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Bicho de Pé com Brigadeiro', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Bicho de Pé com morango', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Chocomix', 'bolo', 129.00, 'Limão e chocolate. Preço por kg'),
  ('Bolo Iogurte com Morango', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Limão com chocolate', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Mousse de Chocolate Branco', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Maracujá com Coco', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Nozes', 'bolo', 129.00, 'Nozes e doce de leite. Preço por kg'),
  ('Bolo Olho de sogra', 'bolo', 129.00, 'Ameixa, cocada. Preço por kg'),
  ('Bolo Paçoca', 'bolo', 129.00, 'Brigadeiro, doce de leite e paçoca. Preço por kg'),
  ('Bolo Alpes Suiço', 'bolo', 129.00, 'Chocolate branco, morango, marshmallow. Preço por kg'),
  ('Bolo Beehgui', 'bolo', 129.00, 'Cereja e rum. Preço por kg'),
  ('Bolo Ninho', 'bolo', 129.00, 'Mousse de leite ninho. Preço por kg'),
  ('Bolo Ninho com abacaxi', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Letícia', 'bolo', 129.00, 'Bicho de pé e chocolate. Preço por kg'),
  ('Bolo Trufado', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Trufado branco', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Brigadeiro Branco', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Camafeu de Nozes', 'bolo', 129.00, 'Preço por kg'),
  ('Bolo Delícia de Coco', 'bolo', 129.00, 'Chocolate e cocada. Preço por kg'),
  ('Bolo Ninho com morango', 'bolo', 129.00, 'Preço por kg'),
  -- Bolos por kg (R$ 137)
  ('Bolo Café', 'bolo', 137.00, 'Café e mousse de chocolate. Preço por kg'),
  ('Bolo Ninho com Nutella', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Limão com Brigadeiro Branco', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Sonho de Morango', 'bolo', 137.00, 'Chocolate, Sonho de Valsa, morango. Preço por kg'),
  ('Bolo Maracujá com Brigadeiro Branco', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Morango com Brigadeiro Branco', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Choconozes', 'bolo', 137.00, 'Trufado e nozes. Preço por kg'),
  ('Bolo Trufado Preto de Morango', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Trufado Branco e Preto', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Ouro Branco', 'bolo', 137.00, 'Brigadeiro e Ouro Branco. Preço por kg'),
  ('Bolo Ovomaltine', 'bolo', 137.00, 'Mousse e ovomaltine. Preço por kg'),
  ('Bolo Trufado Branco de Morango', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Nutella com Brigadeiro Branco', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Chocoberry', 'bolo', 137.00, 'Brigadeiro branco e morango. Preço por kg'),
  ('Bolo Delicia de Mousse Branco', 'bolo', 137.00, 'Morango e geleia. Preço por kg'),
  ('Bolo Trufado de Ninho', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Cappuccino', 'bolo', 137.00, 'Café e canela. Preço por kg'),
  ('Bolo Trufado com Crocante', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Duo (Brigadeiro branco e preto)', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Surpresa de Uva', 'bolo', 137.00, 'Brigadeiro branco e uva. Preço por kg'),
  ('Bolo Napolitano', 'bolo', 137.00, 'Bicho de pé e mousse branco. Preço por kg'),
  ('Bolo Cherry Branco', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Choconinho', 'bolo', 137.00, 'Chocolate e ninho. Preço por kg'),
  ('Bolo Cherry Preto', 'bolo', 137.00, 'Preço por kg'),
  ('Bolo Jufeh', 'bolo', 137.00, 'Chocolate e doce de leite. Preço por kg'),
  ('Bolo Doce Tentação', 'bolo', 137.00, 'Chocolate, morango, brigadeiro branco. Preço por kg'),
  -- Encomendas (cento)
  ('Docinho Brigadeiro (cento)', 'doce', 190.00, 'Encomenda'),
  ('Docinho Beijinho (cento)', 'doce', 190.00, 'Encomenda'),
  ('Docinho Bicho de pé (cento)', 'doce', 190.00, 'Encomenda'),
  ('Docinho Olho de Sogra (cento)', 'doce', 190.00, 'Encomenda'),
  ('Empada de frango (cento)', 'salgado', 190.00, 'Encomenda'),
  ('Empada de palmito (cento)', 'salgado', 190.00, 'Encomenda'),
  ('Bolinho de carne (cento)', 'salgado', 175.00, 'Encomenda'),
  ('Bolinho de queijo (cento)', 'salgado', 175.00, 'Encomenda'),
  ('Coxinha (cento)', 'salgado', 175.00, 'Encomenda'),
  ('Esfiha de carne (cento)', 'salgado', 175.00, 'Encomenda'),
  ('Esfiha de frango (cento)', 'salgado', 175.00, 'Encomenda'),
  ('Esfiha de calabresa (cento)', 'salgado', 175.00, 'Encomenda'),
  ('Kibe (cento)', 'salgado', 175.00, 'Encomenda'),
  ('Risoles (cento)', 'salgado', 175.00, 'Encomenda')
) AS v(name, category, sale_price, description)
WHERE NOT EXISTS (
  SELECT 1 FROM public.recipes r
  WHERE LOWER(TRIM(r.name)) = LOWER(TRIM(v.name))
);
